name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"🚀 Novo push realizado na branch main do repositório ${{ github.repository }} por ${{ github.actor }}.\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}